//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMamNon.modeTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DichVu_HocSinh
    {
        public int MaHocSinh { get; set; }
        public int MaDV { get; set; }
        public Nullable<System.DateTime> NgayDK { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DichVuNgoai DichVuNgoai { get; set; }
        public virtual HocSinh HocSinh { get; set; }
    }
}
