//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMamNon.modeTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHoaDon { get; set; }
        public string TenHoaDon { get; set; }
        public Nullable<System.DateTime> NgayGiaoDich { get; set; }
        public string MaNhanVien { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
