//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMamNon.modeTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLMamNonEntities : DbContext
    {
        public QLMamNonEntities()
            : base("name=QLMamNonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChucVu> ChucVu { get; set; }
        public virtual DbSet<CT_DichVu_HocSinh> CT_DichVu_HocSinh { get; set; }
        public virtual DbSet<CT_NgayTheoDoi> CT_NgayTheoDoi { get; set; }
        public virtual DbSet<DichVuNgoai> DichVuNgoai { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<HocSinh> HocSinh { get; set; }
        public virtual DbSet<LoaiLop> LoaiLop { get; set; }
        public virtual DbSet<Lop> Lop { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<PhieuTheoDoi> PhieuTheoDoi { get; set; }
        public virtual DbSet<PhieuThu> PhieuThu { get; set; }
        public virtual DbSet<Quyen> Quyen { get; set; }
        public virtual DbSet<Quyen_ChucVu> Quyen_ChucVu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
