//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMamNon.modeTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThu
    {
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public int MaHocSinh { get; set; }
        public string MaNhanVien { get; set; }
        public Nullable<int> SoNgayVang { get; set; }
        public Nullable<int> SoNgayAnSang { get; set; }
        public Nullable<int> SoNgayAnTrua { get; set; }
        public string GhiChu { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
