//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMamNon.modeTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quyen_ChucVu
    {
        public string MaQuyen { get; set; }
        public string MaChucVu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
