//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_NgayTheoDoi
    {
        public int MaPhieuTheoDoi { get; set; }
        public string MaHocSinh { get; set; }
        public bool DDVang { get; set; }
        public bool DDAnSang { get; set; }
        public bool DDAnTrua { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
        public virtual PhieuTheoDoi PhieuTheoDoi { get; set; }
    }
}
