//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocPhi
    {
        public string MaHocPhi { get; set; }
        public string TenHocPhi { get; set; }
        public decimal ChiPhi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> LoaiHocphi { get; set; }
    
        public virtual LoaiHocPhi LoaiHocPhi1 { get; set; }
    }
}
