//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocSinh()
        {
            this.CT_NgayTheoDoi = new HashSet<CT_NgayTheoDoi>();
            this.PhieuThu = new HashSet<PhieuThu>();
            this.CT_DichVu_HocSinh = new HashSet<CT_DichVu_HocSinh>();
        }
    
        public int MaHocSinh { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> ChieuCao { get; set; }
        public Nullable<int> CanNang { get; set; }
        public string TenPhuHuynh { get; set; }
        public string SoCmt { get; set; }
        public string Sdt { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgaySinhPhuHuynh { get; set; }
        public string GhiChu { get; set; }
        public string MaLop { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_NgayTheoDoi> CT_NgayTheoDoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuThu> PhieuThu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DichVu_HocSinh> CT_DichVu_HocSinh { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
