//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoanThuDauNam
    {
        public int MaKhoanThu { get; set; }
        public string TenKhoanThu { get; set; }
        public decimal ChiPhi { get; set; }
        public string Year { get; set; }
    }
}
