//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTheoDoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuTheoDoi()
        {
            this.CT_NgayTheoDoi = new HashSet<CT_NgayTheoDoi>();
        }
    
        public int MaPhieuTheoDoi { get; set; }
        public string MaGiaoVien { get; set; }
        public System.DateTime NgayTheoDoi { get; set; }
        public Nullable<decimal> ChiPhiDuTinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_NgayTheoDoi> CT_NgayTheoDoi { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
