//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThu
    {
        public string NgayTaoPhieu { get; set; }
        public string MaHocSinh { get; set; }
        public string MaNhanVien { get; set; }
        public int SoNgayVang { get; set; }
        public int SoNgayAnSang { get; set; }
        public int SoNgayAnTrua { get; set; }
        public decimal ChiPhi { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
